spring:
  application:
    name: ordersService

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

server:
  servlet:
    context-path: /api/order